version: "2.3"

services:

  nucleus:
    container_name: nucleus
    build:
      context: .
      dockerfile: Dockerfile
      target: nucleus
      args:
        BASE_IMAGE: elementaryrobotics/atom:v1.7.1-base-stock-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - "./:/metrics"
    ports:
      - "6379:6379"
      - "6380:6380"

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - "GF_INSTALL_PLUGINS=redis-datasource"
    ports:
      - "3001:3000"

  atom:
    container_name: atom
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        BASE_IMAGE: elementaryrobotics/atom:v1.7.1-base-stock-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/atom"
    depends_on:
      - "nucleus"
    ports:
      - "6080:6080"
    environment:
      - "GRAPHICS=1"
    command: tail -f /dev/null
    # Uncomment to run GDB
    #privileged: true

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
