version: "2.3"

services:

  nucleus:
    container_name: nucleus
    build:
      context: .
      dockerfile: Dockerfile
      target: nucleus
      args:
        BASE_IMAGE: elementaryrobotics/atom:v1.7.2-base-stock-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      # Link in the database
      - "./metrics/metrics.rdb:/metrics/metrics.rdb"
      # Need to see /proc for psutil
      - "/proc:/host/proc:ro"
      # Link in the monitoring folder s.t. we can develop
      - "./metrics/monitoring:/usr/local/bin/monitoring"
      # Launch script for debug
      - "./config/nucleus/launch.sh:/atom/launch.sh"
      # Wait for nucleus script, for debug
      - "./utilities/wait_for_nucleus.sh:/usr/local/bin/wait_for_nucleus.sh"
    network_mode: host
    environment:
      - "METRICS_MONITOR_PROCFS=/host/proc"
      - "ATOM_USE_METRICS=TRUE"
    privileged: true

  metrics:
    container_name: metrics
    build:
      context: metrics
      dockerfile: Dockerfile
    volumes:
      # Link in the dashboards s.t. we can develop
      - "./metrics/dashboards:/metrics/dashboards"
    network_mode: "service:nucleus"

  atom:
    container_name: atom
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        BASE_IMAGE: elementaryrobotics/atom:v1.7.2-base-opencv-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/atom"
    network_mode: host
    depends_on:
      - "nucleus"
    environment:
      - "ATOM_USE_METRICS=TRUE"
    command: tail -f /dev/null

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
