version: "2.3"

services:

  nucleus:
    container_name: nucleus
    build:
      context: .
      dockerfile: Dockerfile
      target: nucleus
      args:
        BASE_IMAGE: elementaryrobotics/atom:base
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true

  atom:
    container_name: atom
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        BASE_IMAGE: elementaryrobotics/atom:base
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/atom"
    depends_on:
      - "nucleus"
    ports:
      - "6080:6080"
    environment:
      - "GRAPHICS=1"
    command: tail -f /dev/null
    # Uncomment to run GDB
    #privileged: true

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
