version: "2.3"

services:

  nucleus:
    container_name: nucleus
    build:
      context: .
      dockerfile: Dockerfile
      target: nucleus
      args:
        BASE_IMAGE: elementaryrobotics/atom:v1.7.2-base-stock-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - "./:/metrics"
      - "/proc:/host_proc:ro"
      - "./metrics/monitoring:/usr/local/bin/monitoring"
    network_mode: host
    environment:
      - "METRICS_MONITOR_PROCFS=/host_proc"
      - "ATOM_USE_METRICS=TRUE"
    privileged: true

  metrics:
    container_name: metrics
    build:
      context: metrics
      dockerfile: Dockerfile
    volumes:
      - "./metrics/dashboards:/metrics/dashboards"
    network_mode: "service:nucleus"

  atom:
    container_name: atom
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        BASE_IMAGE: elementaryrobotics/atom:v1.7.2-base-opencv-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/atom"
    network_mode: host
    depends_on:
      - "nucleus"
    environment:
      - "ATOM_USE_METRICS=TRUE"
    command: tail -f /dev/null

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
