version: "2.3"

services:

  nucleus-arm:
    container_name: nucleus-arm
    image: elementaryrobotics/nucleus:aarch64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - log:/var/log/atom

  atom-arm:
    container_name: atom-arm
    image: elementaryrobotics/atom:aarch64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/atom"
      - log:/var/log/atom
    depends_on:
      - "nucleus-arm"
    ports:
      - "6080:6080"
    environment:
      - "GRAPHICS=1"
    command: tail -f /dev/null

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
  log: 
    driver_opts: 
      type: tmpfs
      device: tmpfs
