version: "2.3"

services:

  nucleus:
    container_name: nucleus
    #image: elementaryrobotics/nucleus
    build:
      context: .
      dockerfile: Dockerfile
      target: nucleus
      args:
        BASE_IMAGE: elementaryrobotics/atom:v1.7.2-base-stock-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - "./:/metrics"
    ports:
      - "6379:6379"
      - "6380:6380"
      - "3001:3000"

  metrics:
    container_name: metrics
    build:
      context: metrics
      dockerfile: Dockerfile
    network_mode: "service:nucleus"

  atom:
    container_name: atom
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        BASE_IMAGE: elementaryrobotics/atom:v1.7.2-base-opencv-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/atom"
      - "/proc:/host_proc"
    network_mode: host
    depends_on:
      - "nucleus"
    environment:
      - "METRICS_MONITOR_PROCFS=/host_proc"
      - "ATOM_USE_METRICS=TRUE"
    command: tail -f /dev/null
    privileged: true

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
