version: "2.3"

services:

  nucleus:
    container_name: nucleus
    image: elementaryrobotics/nucleus
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - log:/var/log/atom

  atom:
    container_name: atom
    image: elementaryrobotics/atom
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/atom"
      - log:/var/log/atom
    depends_on:
      - "nucleus"
    ports:
      - "6080:6080"
    environment:
      - "GRAPHICS=1"
    command: tail -f /dev/null

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
  log: 
    driver_opts: 
      type: tmpfs
      device: tmpfs
