version: "3.2"

services:

  nucleus:
    container_name: nucleus
    image: elementaryrobotics/nucleus
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true

  atom:
    container_name: atom
    image: elementaryrobotics/atom
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
    depends_on:
      - "nucleus"
    command: "tail -f /dev/null"

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
