version: 2.1
description: Commands useful for building/deploying elements

#
# Machines that can be used for build. Build-classic is typically
# what you want to use.
#
executors:

  # Machine used to build docker containers using the
  # CircleCI classic image
  build-classic:
    machine:
      enabled: true
      docker_layer_caching: true
      image: circleci/classic:201808-01

  # Ubuntu 16.04 machine used to build some images
  build-ubuntu:
    machine:
      enabled: true
      docker_layer_caching: true
      image: ubuntu-1604:201903-01

#
# Commands that are useful for build and deploy
#
commands:

  # Log into docker
  docker_login:
    description: "Logs into Dockerhub"
    steps:
      - run:
          name: Docker Login
          command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin

  # Load image from workspace and log into docker
  load_and_login:
    description: "Load the image from workspace and login"
    parameters:
      image_name:
        type: string
        default: image
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker Image
          command: docker load -i /tmp/workspace/<< parameters.image_name >>.tar
      - docker_login

  # Build and launch the docker-compose file
  build_and_launch:
    description: "Build and launch the docker-compose file"
    parameters:
      file:
        type: string
      service:
        type: string
    steps:
      - run:
          name: Build Docker Compose File
          command: docker-compose -p atom -f << parameters.file >> build --no-cache --pull
      - run:
          name: Tag built service
          command: docker tag atom_<< parameters.service >>:latest ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_WORKFLOW_ID}
      - run:
          name: Launch Docker Compose File
          command: docker-compose -p atom -f << parameters.file >> up -d

  # Store the docker image
  store_image:
    description: "Store the image built"
    parameters:
      image_filename:
        type: string
        default: image
    steps:
      - run:
          name: Archive Docker image
          command: docker save -o << parameters.image_filename >>.tar ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_WORKFLOW_ID}
      - persist_to_workspace:
          root: .
          paths:
            - ./ << parameters.image_filename >>.tar
      - store_artifacts:
          path: ./ << parameters.image_filename >>.tar

  # Create and push image tag
  tag_and_deploy:
    description: "Tag the latest docker image and deploy it"
    parameters:
      tag:
        type: string
      source_image:
        type: string
        default: ${CIRCLE_PROJECT_REPONAME}-${CIRCLE_WORKFLOW_ID}
      target_image:
        type: string
        default: ${DOCKERHUB_ORG}/${DOCKERHUB_REPO}
    steps:
      - run:
          name: Docker Tag
          command: docker tag << parameters.source_image >> << parameters.target_image >>:<< parameters.tag >>
      - run:
          name: Docker Push
          command: docker push << parameters.target_image >>:<< parameters.tag >>

  push_dev_image:
    parameters:
      image_filename:
        type: string
      source_image:
        type: string
      target_image:
        type: string
    steps:
      - load_and_login:
          image_name: << parameters.image_filename >>
      - tag_and_deploy:
          tag: development-${CIRCLE_BUILD_NUM}
          source_image: << parameters.source_image >>
          target_image: << parameters.target_image >>

  push_master_image:
    parameters:
      image_name:
        type: string
        default: image
    steps:
      - load_and_login:
          image_name: << parameters.image_name >>
      - tag_and_deploy:
          tag: master-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}
      - tag_and_deploy:
          tag: latest

  push_tag_image:
    parameters:
      image_name:
        type: string
        default: image
    steps:
      - load_and_login:
          image_name: << parameters.image_name >>
      - tag_and_deploy:
          tag: ${CIRCLE_TAG}


#
# Jobs that are nice to be able to share between elements
#
jobs:

  # Tag and deploy a development image
  deploy-dev:
    executor: build-classic
    parameters:
      image_name:
        type: string
        default: image
    steps:
      - push_dev_image:
          image_name: << parameters.image_name >>

  # Tag and deploy a master image
  deploy-master:
    executor: build-classic
    parameters:
      image_name:
        type: string
        default: image
    steps:
      - push_master_image:
          image_name: << parameters.image_name >>

  # Tag and deploy release image with GitHub tag
  deploy-tag:
    executor: build-classic
    parameters:
      image_name:
        type: string
        default: image
    steps:
      - push_tag_image:
           image_name: << parameters.image_name >>


#
# Examples
#
examples:
  standard-build:

    description: General-purpose build, and deploy

    usage:
      version: 2.1

      orbs:
        atom: elementaryrobotics/atom@x.y.z

      jobs:
        build:
          executor: atom/build-classic
          environment:
            DOCKER_COMPOSE_SERVICE_NAME: some_service
          steps:
            - checkout
            - atom/docker_login
            - atom/build_and_launch:
                file: docker-compose.yml
                service: ${DOCKER_COMPOSE_SERVICE_NAME}
            - run:
                name: Unit Tests
                command: docker exec -it ${DOCKER_COMPOSE_SERVICE_NAME} $my_unit_test_command
            - atom/store_image

      workflows:
        version: 2
        build-all:
          jobs:
            - build
            - atom/deploy-master:
                requires:
                  - build
                filters:
                  branches:
                    only:
                      - master
                  tags:
                    only: /.*/
            - atom/deploy-tag:
                requires:
                  - build
                filters:
                  branches:
                    ignore:
                      - /.*/
                  tags:
                    only: /.*/
            - atom/deploy-dev:
                requires:
                  - build
                filters:
                  branches:
                    ignore:
                      - master
