# .circleci/config.yml

#
# Section for setting repeatedly used yaml anchors/aliases
#
aliases:
  - &atom_build_vars
      DOCKER_COMPOSE_PROJECT_NAME: atom
      DOCKER_COMPOSE_ATOM_SERVICE_NAME: atom
      DOCKER_COMPOSE_NUCLEUS_SERVICE_NAME: nucleus
      DOCKER_COMPOSE_ATOM_CONTAINER_NAME: dev_atom
      DOCKER_COMPOSE_NUCLEUS_CONTAINER_NAME: dev_nucleus
  - &atom_image_names
      image_filename: ${DOCKERHUB_ATOM_REPO}
      source_image: ${DOCKERHUB_ATOM_REPO}-${CIRCLE_WORKFLOW_ID}
      target_image: ${DOCKERHUB_ORG}/${DOCKERHUB_ATOM_REPO}
  - &cuda_image_names
      image_filename: ${DOCKERHUB_ATOM_CUDA_10_REPO}
      source_image: ${DOCKERHUB_ATOM_CUDA_10_REPO}-${CIRCLE_WORKFLOW_ID}
      target_image: ${DOCKERHUB_ORG}/${DOCKERHUB_ATOM_CUDA_10_REPO}
  - &opengl_image_names
      image_filename: ${DOCKERHUB_ATOM_OPENGL_REPO}
      source_image: ${DOCKERHUB_ATOM_OPENGL_REPO}-${CIRCLE_WORKFLOW_ID}
      target_image: ${DOCKERHUB_ORG}/${DOCKERHUB_ATOM_OPENGL_REPO}
  - &opengl_cuda_image_names
      image_filename: ${DOCKERHUB_ATOM_OPENGL_CUDA_10_REPO}
      source_image: ${DOCKERHUB_ATOM_OPENGL_CUDA_10_REPO}-${CIRCLE_WORKFLOW_ID}
      target_image: ${DOCKERHUB_ORG}/${DOCKERHUB_ATOM_OPENGL_CUDA_10_REPO}
  - &nucleus_image_names
      image_filename: ${DOCKERHUB_NUCLEUS_REPO}
      source_image: atom_${DOCKER_COMPOSE_NUCLEUS_SERVICE_NAME}-${CIRCLE_WORKFLOW_ID}
      target_image: ${DOCKERHUB_ORG}/${DOCKERHUB_NUCLEUS_REPO}
  - &docs_env
      DOCKER_COMPOSE_PROJECT_NAME: docs
      DOCKER_COMPOSE_SERVICE_NAME: docs
  - &docs_image_names
      image_filename: ${DOCKER_COMPOSE_SERVICE_NAME}
      source_image: ${DOCKERHUB_ORG}/${DOCKERHUB_DOCS_REPO}:build-${CIRCLE_WORKFLOW_ID}
      target_image: ${DOCKERHUB_ORG}/${DOCKERHUB_DOCS_REPO}


#
# Circle config
#
version: 2.1

orbs:
  atom:  elementaryrobotics/atom@dev:251

jobs:
  build-atom:
    executor: atom/build-classic
    resource_class: large
    environment:
      <<: *atom_build_vars
    steps:
      - checkout
      - update_submodules
      - atom/docker_login

      # Build, launch, and save docker image
      - atom/build_and_launch:
          file: docker-compose.yml
          service: ${DOCKER_COMPOSE_ATOM_SERVICE_NAME}
          image_tag: ${DOCKERHUB_ATOM_REPO}-${CIRCLE_WORKFLOW_ID}
      # Tag and save nucleus image
      - run:
          name: Tag nucleus image
          command: docker tag ${DOCKER_COMPOSE_PROJECT_NAME}_${DOCKER_COMPOSE_NUCLEUS_SERVICE_NAME} ${DOCKER_COMPOSE_PROJECT_NAME}_${DOCKER_COMPOSE_NUCLEUS_SERVICE_NAME}-${CIRCLE_WORKFLOW_ID}
      - run_tests:
          container: ${DOCKER_COMPOSE_ATOM_CONTAINER_NAME}

  build-cuda:
    executor: atom/build-classic
    resource_class: large
    environment:
      <<: *atom_build_vars
    steps:
      - checkout
      - update_submodules
      - atom/docker_login
      - atom/build_and_launch:
          file: docker-compose-circle.yml
          service: ${DOCKER_COMPOSE_ATOM_SERVICE_NAME}
          image_tag: ${DOCKERHUB_ATOM_CUDA_10_REPO}-${CIRCLE_WORKFLOW_ID}
          build_args: BASE_IMAGE=atom-cuda-10-base
      - run_tests:
          container: ${DOCKER_COMPOSE_ATOM_CONTAINER_NAME}

  build-opengl:
    executor: atom/build-classic
    resource_class: large
    environment:
      <<: *atom_build_vars
    steps:
      - checkout
      - update_submodules
      - atom/docker_login
      - atom/build_and_launch:
          file: docker-compose-circle.yml
          service: ${DOCKER_COMPOSE_ATOM_SERVICE_NAME}
          image_tag: ${DOCKERHUB_ATOM_OPENGL_REPO}-${CIRCLE_WORKFLOW_ID}
          build_args: BASE_IMAGE=atom-opengl-base
      - run_tests:
          container: ${DOCKER_COMPOSE_ATOM_CONTAINER_NAME}

  build-opengl-cuda:
    executor: atom/build-classic
    resource_class: large
    environment:
      <<: *atom_build_vars
    steps:
      - checkout
      - update_submodules
      - atom/docker_login
      - atom/build_and_launch:
          file: docker-compose-circle.yml
          service: ${DOCKER_COMPOSE_ATOM_SERVICE_NAME}
          image_tag: ${DOCKERHUB_ATOM_OPENGL_CUDA_10_REPO}-${CIRCLE_WORKFLOW_ID}
          build_args: BASE_IMAGE=atom-opengl-cuda-10-base
      - run_tests:
          container: ${DOCKER_COMPOSE_ATOM_CONTAINER_NAME}

  deploy-dev:
    executor: atom/build-classic
    resource_class: large
    environment:
      <<: *atom_build_vars
    steps:
      - atom/docker_login
      - atom/push_dev_image:
          <<: *atom_image_names
      - atom/push_dev_image:
          <<: *cuda_image_names
      - atom/push_dev_image:
          <<: *opengl_image_names
      - atom/push_dev_image:
          <<: *opengl_cuda_image_names
      - atom/push_dev_image:
          <<: *nucleus_image_names

  deploy-master:
    executor: atom/build-classic
    environment:
      <<: *atom_build_vars
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - atom/docker_login
      - atom/push_master_image:
          <<: *atom_image_names
      - atom/push_master_image:
          <<: *cuda_image_names
      - atom/push_master_image:
          <<: *opengl_image_names
      - atom/push_master_image:
          <<: *opengl_cuda_image_names
      - atom/push_master_image:
          <<: *nucleus_image_names

  deploy-tag:
    executor: atom/build-classic
    environment:
      <<: *atom_build_vars
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - atom/docker_login
      - atom/push_tag_image:
          <<: *atom_image_names
      - atom/push_tag_image:
          <<: *cuda_image_names
      - atom/push_tag_image:
          <<: *opengl_image_names
      - atom/push_tag_image:
          <<: *opengl_cuda_image_names
      - atom/push_tag_image:
          <<: *nucleus_image_names

  build-docs:
    executor: atom/build-classic
    environment:
      <<: *docs_env
    steps:
      - checkout

      # Need to log into docker
      - atom/docker_login

      #
      # Build docker image
      #
      - run:
          working_directory: doc
          name: Build docker
          command: docker-compose -f docker-compose-test.yml -p ${DOCKER_COMPOSE_PROJECT_NAME} build --pull
      - run:
          name: Tag Docker Image
          command: docker tag ${DOCKER_COMPOSE_PROJECT_NAME}_${DOCKER_COMPOSE_SERVICE_NAME} ${DOCKER_COMPOSE_PROJECT_NAME}_${DOCKER_COMPOSE_SERVICE_NAME}-${CIRCLE_WORKFLOW_ID}
      - run:
          command: |
            docker tag ${DOCKER_COMPOSE_PROJECT_NAME}_${DOCKER_COMPOSE_SERVICE_NAME} ${DOCKERHUB_ORG}/${DOCKERHUB_DOCS_REPO}:build-${CIRCLE_WORKFLOW_ID}
            docker push ${DOCKERHUB_ORG}/${DOCKERHUB_DOCS_REPO}:build-${CIRCLE_WORKFLOW_ID}

  deploy-dev-docs:
    executor: atom/build-classic
    environment:
      <<: *docs_env
    steps:
      - atom/docker_login
      - run:
          command: |
            docker pull ${DOCKERHUB_ORG}/${DOCKERHUB_DOCS_REPO}:build-${CIRCLE_WORKFLOW_ID}
      - atom/push_dev_image:
          <<: *docs_image_names

  deploy-master-docs:
    executor: atom/build-classic
    environment:
      <<: *docs_env
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - atom/docker_login
      - atom/push_master_image:
          <<: *docs_image_names
      - heroku_deploy:
          image_tag: ${DOCKERHUB_ORG}/${DOCKERHUB_DOCS_REPO}

  deploy-tag-docs:
    executor: atom/build-classic
    environment:
      <<: *docs_env
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - atom/docker_login
      - atom/push_tag_image:
          <<: *docs_image_names
      - heroku_deploy:
          image_tag: ${DOCKERHUB_ORG}/${DOCKERHUB_DOCS_REPO}


commands:

  run_tests:
    parameters:
      container:
        type: string
    steps:
      - run:
          name: Python tests
          command: docker exec -it -w /atom/languages/python/tests << parameters.container >> pytest
      - run:
          name: C tests
          command:  docker exec -it -w /atom/languages/c << parameters.container >> make test
      - run:
          name: C++ tests
          command:  docker exec -it -w /atom/languages/cpp << parameters.container >> make test
      - run:
          name: C++ valgrind check
          command: docker exec -it -w /atom/languages/cpp << parameters.container >> valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --log-file=valgrind.log --error-exitcode=1 test/build/test_atom_cpp
          environment:
            G_SLICE: always-malloc
            G_DEBUG: gc-friendly
      - run:
          name: C++ copy valgrind log
          command: docker cp << parameters.container >>:/atom/languages/cpp/valgrind.log /tmp/valgrind.log
      - store_artifacts:
          path: /tmp/valgrind.log
          destination: valgrind.log

  heroku_deploy:
    parameters:
      image_tag:
        type: string
    steps:
      - run:
          command: |
            docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
            docker tag << parameters.image_tag >> registry.heroku.com/${HEROKU_APP_NAME}/web
            docker push registry.heroku.com/${HEROKU_APP_NAME}/web
            heroku container:release -a ${HEROKU_APP_NAME} web

  update_submodules:
    steps:
      - run:
          name: Update Submodules
          command: git submodule update --init --recursive


workflows:
  version: 2
  commit:
    jobs:
      - build-atom:
          filters:
            tags:
              only: /.*/
      - build-docs:
          filters:
            tags:
              only: /.*/
      # Build special images after tests pass for atom
      - build-opengl:
          requires:
            - build-atom
          filters:
            tags:
              only: /.*/
      - build-cuda:
          requires:
            - build-atom
          filters:
            tags:
              only: /.*/
      - build-opengl-cuda:
          requires:
            - build-atom
          filters:
            tags:
              only: /.*/

      # Deploy all images after all tests pass
      - deploy-master:
          requires:
            - build-opengl
            - build-cuda
            - build-opengl-cuda
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
      - deploy-tag:
          requires:
            - build-opengl
            - build-cuda
            - build-opengl-cuda
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /.*/
      - deploy-dev:
          requires:
            - build-opengl
            - build-cuda
            - build-opengl-cuda
          filters:
            branches:
              ignore:
                - master

      # Deploy docs
      - deploy-master-docs:
          requires:
            - build-docs
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
      - deploy-tag-docs:
          requires:
            - build-docs
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /.*/
      - deploy-dev-docs:
          requires:
            - build-docs
          filters:
            branches:
              ignore:
                - master

  nightly:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-docs
      - deploy-dev-docs:
          requires:
            - build-docs
          filters:
            branches:
              ignore:
                - master
