version: "3.2"

services:

  nucleus:
    container_name: test_nucleus
    image: $NUCLEUS_IMAGE
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - log:/var/log/atom
    environment:
      - "NUCLEUS_METRICS_MONITOR=FALSE"
      - "ATOM_USE_METRICS=TRUE"

  atom:
    container_name: test_atom
    image: $ATOM_IMAGE
    network_mode: "service:nucleus"
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - log:/var/log/atom
    depends_on:
      - "nucleus"
    environment:
      - "GRAPHICS=1"
      - "ATOM_USE_METRICS=TRUE"
    command: tail -f /dev/null

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
  log: 
    driver_opts: 
      type: tmpfs
      device: tmpfs
