version: "3.2"

services:

  nucleus:
    container_name: nucleus
    image: elementaryrobotics/nucleus
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
    command: ./launch.sh

  atombot:
    container_name: atombot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - /home/elementary/src/atom/doc/files/walkthrough:/code:rw
    depends_on:
      - "nucleus"

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
