  version: 2.1

  orbs:
    atom: elementaryrobotics/atom@0.0.1

  jobs:
    build:
      executor: atom/build-classic
      environment:
        DOCKER_COMPOSE_SERVICE_NAME: some_service
      steps:
        - checkout
        - atom/docker_login
        - atom/build_and_launch:
            file: docker-compose.yml
            service: ${DOCKER_COMPOSE_SERVICE_NAME}
        - run:
            name: Unit Tests
            command: docker exec -it ${DOCKER_COMPOSE_SERVICE_NAME} $my_unit_test_command
        - atom/store_image

  workflows:
    version: 2
    build-all:
      jobs:
        - build
        - atom/deploy-master:
            requires:
              - build
            filters:
              branches:
                only:
                  - master
        - atom/deploy-dev:
            requires:
              - build
            filters:
              branches:
                ignore:
                  - master
