version: 2.1

parameters:
  atom_repo:
    type: string
    default: elementaryrobotics/atom
  atom_version:
    type: string
    default: v1.3.0
  dockerhub_repo:
    type: string
    default: elementaryrobotics/example-element

orbs:
  atom: elementaryrobotics/atom@0.1.3

workflows:
  version: 2
  build-all:
    jobs:

      # Build for intel and ARM
      - atom/build_buildx:
          name: "build-<< matrix.platform >>"
          matrix:
            parameters:
              variant: [ stock ]
              platform: [ amd64, aarch64 ]
          image_name: << pipeline.parameters.dockerhub_repo >>
          image_tag: build-<< pipeline.number >>
          cache_repo: << pipeline.parameters.dockerhub_repo >>
          cache_tag: cache
          build_args: --build-arg ATOM_IMAGE=<< pipeline.parameters.atom_repo >>:<< pipeline.parameters.atom_version >>-<< matrix.variant >>-<< matrix.platform >>
          filters:
            tags:
              only: /.*/

      # Test
      - atom/test:
          name: "test-<< matrix.platform >>"
          matrix:
            parameters:
              variant: [ stock ]
              platform: [ amd64, aarch64 ]
          test_image: << pipeline.parameters.dockerhub_repo >>
          test_tag: build-<< pipeline.number >>
          atom_version: << pipeline.parameters.atom_version >>
          compose_file: .circleci/docker-compose.yml
          container_name: test-container
          container_test_dir: /code
          test_cmd: echo "write some tests!"
          requires:
            - build-<< matrix.platform >>
          filters:
            tags:
              only: /.*/

      # Check Flake8 -- parallel to the build
      - atom/check_flake8:
          version: 3.7.0
          exclude: tests/*,tasks/elementary-task,robot-shared
          filters:
            tags:
              only: /.*/

      # Deploy development
      - atom/deploy:
          name: "deploy-development-<< matrix.platform >>"
          source_image: << pipeline.parameters.dockerhub_repo >>
          source_tag: build-<< pipeline.number >>
          target_image: << pipeline.parameters.dockerhub_repo >>
          target_tag: development-<< pipeline.number >>
          matrix:
            parameters:
              variant: [ stock ]
              platform: [ amd64, aarch64 ]
          requires:
            - build-<< matrix.platform >>
          filters:
            branches:
              ignore:
                - master

      # Deploy Master
      - atom/deploy:
          name: "deploy-master-<< matrix.platform >>"
          source_image: << pipeline.parameters.dockerhub_repo >>
          source_tag: build-<< pipeline.number >>
          target_image: << pipeline.parameters.dockerhub_repo >>
          target_tag: master-<< pipeline.number >>
          matrix:
            parameters:
              variant: [ stock ]
              platform: [ amd64, aarch64 ]
          requires:
            - build-<< matrix.platform >>
          filters:
            branches:
              only:
                - master

      # Deploy latest
      - atom/deploy_latest:
          name: "deploy-latest-<< matrix.platform >>"
          source_image: << pipeline.parameters.dockerhub_repo >>
          source_tag: build-<< pipeline.number >>
          target_image: << pipeline.parameters.dockerhub_repo >>
          matrix:
            parameters:
              variant: [ stock ]
              platform: [ amd64, aarch64 ]
          requires:
            - build-<< matrix.platform >>
          filters:
            branches:
              only:
                - master

      # Deploy tag
      - atom/deploy:
          name: "deploy-tag-<< matrix.platform >>"
          source_image: << pipeline.parameters.dockerhub_repo >>
          source_tag: build-<< pipeline.number >>
          target_image: << pipeline.parameters.dockerhub_repo >>
          target_tag: ${CIRCLE_TAG}
          matrix:
            parameters:
              variant: [ stock ]
              platform: [ amd64, aarch64 ]
          requires:
            - build-<< matrix.platform >>
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /.*/
