version: "2.3"

services:

  grafana:
    container_name: grafana
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./grafana-redis-datasource:/tmp/grafana-redis-datasource"
    ports:
      - "3001:3000"
